org: landonmccleary
app: dd-group-finder
console: true
service: dd-group-finder
configValidationMode: warn
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev 

custom:
  region: us-east-1
  secret: c902c29b38433efb12aa43e05606b9489c3e60cff4498e4dcf240267b66651c3

plugins:
  - serverless-offline

functions:
  # user:
  #   handler: user.html
  #   events:
  #     - http:
  #         path: /user-page
  #         method: get
  # group:
  #   handler: group.html
  #   events:
  #     - http:
  #         path: /group-page
  #         method: get
  # character:
  #   handler: character.html
  #   events:
  #     - http:
  #         path: /character-page
  #         method: get
  # posts:
  #   handler: posts.html
  #   events:
  #     - http:
  #         path: /posts-page
  #         method: get
  # search:
  #   handler: search.html
  #   events:
  #     - http:
  #         path: /search
  #         method: get
  # createGroup:
  #   handler: createGroup.html
  #   events:
  #     - http:
  #         path: /create-group
  #         method: get 
  # createChar:
  #   handler: createChar.html
  #   events:
  #     - http:
  #         path: /create-char
  #         method: get
  app:
    handler: lambda.express
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true